version: '3'

tasks:
  task-with-summary:
    summary: |
      summary of task-with-summary - line 1
      line 2
      line 3
    deps:
      - dependent-task-1
      - dependent-task-2
    cmds:
      - echo 'task-with-summary was executed'
      - echo 'another command'
      - exit 0

  other-task-with-summary:
    summary: summary of other-task-with-summary
    cmds:
      - echo 'other-task-with-summary was executed'
